[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xff938a"
index = 17

[colors.bright]
black = "0x636e7b"
blue = "0x6cb6ff"
cyan = "0x56d4dd"
green = "0x6bc46d"
magenta = "0xdcbdfb"
red = "0xff938a"
white = "0x768390"
yellow = "0xdaaa3f"

[colors.normal]
black = "0x22272e"
blue = "0x6cb6ff"
cyan = "0x56d4dd"
green = "0x6bc46d"
magenta = "0xb083f0"
red = "0xff938a"
white = "0x768390"
yellow = "0xc69026"

# [colors.primary]
# foreground = "0x768390"
# background = "0x22272e"

[colors.primary]
foreground = "#a6b3c0"
background = "#22272e"
